-- Schema do servico de agendamento.
--
-- SQL deliberadamente neutro (sem tipos proprietarios, sem SERIAL): as mesmas migracoes
-- rodam no Postgres em producao e no H2 em MODE=PostgreSQL nos testes. Com
-- ddl-auto=validate, qualquer divergencia entre entidade e DDL quebra o build.

CREATE TABLE usuario (
    id    BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome  VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    role  VARCHAR(20)  NOT NULL
);

-- Paciente e medico compartilham a chave primaria do usuario (@MapsId): o usuario_id do JWT
-- e o mesmo paciente_id que viaja no evento Kafka.
CREATE TABLE paciente (
    id              BIGINT      PRIMARY KEY,
    cpf             VARCHAR(14) NOT NULL UNIQUE,
    telefone        VARCHAR(20),
    data_nascimento DATE,
    CONSTRAINT fk_paciente_usuario FOREIGN KEY (id) REFERENCES usuario (id)
);

CREATE TABLE medico (
    id            BIGINT      PRIMARY KEY,
    crm           VARCHAR(20) NOT NULL UNIQUE,
    especialidade VARCHAR(80) NOT NULL,
    CONSTRAINT fk_medico_usuario FOREIGN KEY (id) REFERENCES usuario (id)
);

CREATE TABLE consulta (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id   BIGINT        NOT NULL,
    medico_id     BIGINT        NOT NULL,
    data_hora     TIMESTAMP     NOT NULL,
    status        VARCHAR(20)   NOT NULL,
    observacoes   VARCHAR(1000),
    versao        BIGINT        NOT NULL,
    criado_em     TIMESTAMP     NOT NULL,
    atualizado_em TIMESTAMP     NOT NULL,
    CONSTRAINT fk_consulta_paciente FOREIGN KEY (paciente_id) REFERENCES paciente (id),
    CONSTRAINT fk_consulta_medico   FOREIGN KEY (medico_id)   REFERENCES medico (id)
);

CREATE INDEX idx_consulta_paciente_data ON consulta (paciente_id, data_hora);

-- Impede double-booking do mesmo medico no mesmo horario no nivel do banco, alem da
-- validacao de servico: duas requisicoes concorrentes nao driblam a regra.
CREATE UNIQUE INDEX uk_consulta_medico_horario ON consulta (medico_id, data_hora);

-- Outbox transacional: gravada junto com a consulta, publicada depois do commit.
CREATE TABLE outbox_evento (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agregado_id  BIGINT       NOT NULL,
    tipo_evento  VARCHAR(40)  NOT NULL,
    payload      TEXT         NOT NULL,
    criado_em    TIMESTAMP    NOT NULL,
    publicado_em TIMESTAMP,
    tentativas   INTEGER      NOT NULL DEFAULT 0,
    ultimo_erro  VARCHAR(500)
);

-- Suporta a consulta do publicador: pendentes (publicado_em IS NULL) em ordem de criacao.
CREATE INDEX idx_outbox_pendente ON outbox_evento (publicado_em, id);
