-- Schema do servico de notificacao. SQL neutro: roda no Postgres e no H2 dos testes.

-- Projecao local das consultas, alimentada pelos eventos do Kafka. A chave primaria e o id da
-- consulta de origem, o que torna o consumo idempotente.
CREATE TABLE consulta_agendada (
    consulta_id          BIGINT       PRIMARY KEY,
    paciente_id          BIGINT       NOT NULL,
    paciente_nome        VARCHAR(120) NOT NULL,
    paciente_email       VARCHAR(150) NOT NULL,
    medico_nome          VARCHAR(120) NOT NULL,
    medico_especialidade VARCHAR(80),
    data_hora            TIMESTAMP    NOT NULL,
    status               VARCHAR(20)  NOT NULL,
    versao               BIGINT       NOT NULL,
    atualizado_em        TIMESTAMP    NOT NULL
);

-- Suporta a varredura do agendador de lembretes.
CREATE INDEX idx_consulta_agendada_status_data ON consulta_agendada (status, data_hora);

CREATE TABLE notificacao (
    id                 BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id        BIGINT        NOT NULL,
    tipo               VARCHAR(20)   NOT NULL,
    destinatario       VARCHAR(150)  NOT NULL,
    assunto            VARCHAR(200)  NOT NULL,
    mensagem           VARCHAR(2000) NOT NULL,
    data_hora_consulta TIMESTAMP     NOT NULL,
    versao_consulta    BIGINT        NOT NULL,
    status             VARCHAR(20)   NOT NULL,
    enviado_em         TIMESTAMP     NOT NULL,
    erro               VARCHAR(500)
);

-- Um indice por guarda de idempotencia: eventos usam a versao do agregado, lembretes usam a
-- data da consulta (remarcar deve gerar um lembrete novo).
CREATE INDEX idx_notificacao_idem_evento   ON notificacao (consulta_id, tipo, versao_consulta, status);
CREATE INDEX idx_notificacao_idem_lembrete ON notificacao (consulta_id, tipo, data_hora_consulta, status);
