-- Schema do servico de historico (read model). SQL neutro: Postgres em producao, H2 nos testes.
--
-- Nao ha lado de escrita aqui: as duas tabelas sao alimentadas apenas pelo consumidor Kafka.

-- Estado atual de cada consulta. A chave primaria e o id de origem: reprocessar um evento
-- sobrescreve a linha em vez de duplicar.
CREATE TABLE consulta_historico (
    consulta_id          BIGINT        PRIMARY KEY,
    paciente_id          BIGINT        NOT NULL,
    paciente_nome        VARCHAR(120)  NOT NULL,
    paciente_email       VARCHAR(150)  NOT NULL,
    medico_id            BIGINT        NOT NULL,
    medico_nome          VARCHAR(120)  NOT NULL,
    medico_especialidade VARCHAR(80),
    data_hora            TIMESTAMP     NOT NULL,
    status               VARCHAR(20)   NOT NULL,
    observacoes          VARCHAR(1000),
    versao               BIGINT        NOT NULL,
    atualizado_em        TIMESTAMP     NOT NULL
);

-- A consulta mais frequente e "historico de um paciente em ordem cronologica".
CREATE INDEX idx_historico_paciente_data ON consulta_historico (paciente_id, data_hora);
CREATE INDEX idx_historico_medico_data   ON consulta_historico (medico_id, data_hora);
CREATE INDEX idx_historico_status        ON consulta_historico (status);

-- Trilha de auditoria append-only: um registro por evento consumido do topico.
CREATE TABLE evento_consulta (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    consulta_id        BIGINT      NOT NULL,
    tipo_evento        VARCHAR(40) NOT NULL,
    status_resultante  VARCHAR(20) NOT NULL,
    data_hora_consulta TIMESTAMP   NOT NULL,
    versao             BIGINT      NOT NULL,
    ocorrido_em        TIMESTAMP   NOT NULL,
    registrado_em      TIMESTAMP   NOT NULL
);

CREATE INDEX idx_evento_consulta ON evento_consulta (consulta_id, versao);

-- Impede que uma reentrega do broker duplique a linha da trilha.
CREATE UNIQUE INDEX uk_evento_consulta_versao ON evento_consulta (consulta_id, versao, tipo_evento);
